services:
  homebox-reminder:
    image: ghcr.io/101br03k/homebox-reminder:latest
    container_name: homebox-reminder
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/data
